name = "MAE150A"
uuid = "a017625c-406c-46ee-99d6-0fac6062339e"
authors = ["Jeff Eldredge <jdeldre@g.ucla.edu>"]
version = "0.1.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Gasdynamics1D = "147bd2d4-5614-4af7-9716-06bc640f25f6"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
ImmersedLayers = "cdc13194-334e-4e1c-bc8d-fc3a28509c85"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PotentialFlow = "73af2aaf-3f58-5b29-82a9-435ecf827f5b"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
ViscousFlow = "103da179-b3e4-57c1-99a4-586354eb2c5a"

[compat]
ColorTypes = "0.10.12, 0.11"
Dierckx = "0.5.1"
Gasdynamics1D = "0.2.0"
IJulia = "1.23"
Interpolations = "0.12.10, 0.13"
LaTeXStrings = "1"
Literate = "2"
PlotUtils = "1"
PotentialFlow = "0.2.6"
Reexport = "0.2.0, 1.0"
Requires = "1"
Roots = "1"
SpecialFunctions = "1"
ViscousFlow = "0.5.3"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
